name: Publish and release

on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: bahmutov/npm-install@v1
            - uses: changesets/action@master
              with:
                  title: Release
                  publish: npm run release
